SELECT ID, FIRST_NAME, LAST_NAME,
CASE When PRODUCT_NAME = 'Cell Phone' THEN 'Mobiles' ELSE PRODUCT_NAME END AS PRODUCT_NAME,
ITEMS_SOLD, SOLD_PRICE, ITEMS_SOLD*SOLD_PRICE as TOTAL_SALES,
CASE When ITEMS_SOLD*SOLD_PRICE >= 3000 THEN 'High' WHEN ITEMS_SOLD*SOLD_PRICE >= 1500 THEN 'Medium' ELSE 'Low' END as Sales_Status,
SOLD_DATE, COUNTRY, REGION
FROM MYDB.ONEDRIVE.TOTAL_SALE_IN
WHERE REGION = 'Europe'
ORDER BY SOLD_PRICE DESC