SELECT T.ID, T.FIRST_NAME, T.LAST_NAME, SP.EXPERIENCEYEARS,
T.ITEMS_SOLD, T.SOLD_PRICE, 
T.SOLD_DATE, T.COUNTRY, T.REGION
FROM MYDB.ONEDRIVE.TOTAL_SALE_IN T
INNER JOIN MYDB.POSTGRES1_MYSCHEMA.SALESPERSON SP ON T.ID = SP.SALEPERSONID